apiVersion: v1
kind: Service
metadata:
  name: {{ include "tor-bridge.fullname" . }}
  labels:
    {{- include "tor-bridge.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - name: orport
      port: {{ .Values.service.orPort }}
      targetPort: orport
    - name: ptport
      port: {{ .Values.service.ptPort }}
      targetPort: ptport
  selector:
    {{- include "tor-bridge.selectorLabels" . | nindent 4 }}